variable "tenancy_ocid" {
  description = "OCI tenancy OCID."
  type        = string
}
variable "current_user_ocid" {
  description = "OCI user OCID used for local execution or bootstrap."
  type        = string
}
variable "region" {
  description = "OCI region name."
  type        = string
}
variable "home_region" {
  description = "OCI tenancy home region."
  type        = string
  default     = null
}
variable "oci_config_profile" {
  description = "Optional OCI CLI config profile for local execution."
  type        = string
  default     = null
}
variable "org" {
  description = "Short organization prefix used in names."
  type        = string
}
variable "environment" {
  description = "Deployment environment name."
  type        = string
}
variable "region_key" {
  description = "Short OCI region key used in resource names."
  type        = string
}
variable "compartment_ocid" {
  description = "Compartment OCID where resources are created. Defaults to tenancy_ocid for validation-only tests."
  type        = string
  default     = null
}
variable "defined_tags" {
  description = "Defined tags applied to resources."
  type        = map(string)
  default     = {}
}
variable "freeform_tags" {
  description = "Freeform tags applied to resources."
  type        = map(string)
  default     = {}
}

variable "create_asset_bucket" {
  description = "Create the private Object Storage asset origin bucket."
  type        = bool
  default     = true
}
variable "existing_asset_bucket_name" {
  description = "Existing Object Storage bucket name when create_asset_bucket is false."
  type        = string
  default     = null
}
variable "asset_bucket_name" {
  description = "Optional Object Storage bucket name override."
  type        = string
  default     = null
}
variable "bucket_storage_tier" {
  description = "Object Storage bucket storage tier."
  type        = string
  default     = "Standard"

  validation {
    condition     = contains(["Standard", "Archive"], var.bucket_storage_tier)
    error_message = "bucket_storage_tier must be Standard or Archive."
  }
}
variable "bucket_versioning" {
  description = "Object Storage versioning setting."
  type        = string
  default     = "Enabled"

  validation {
    condition     = contains(["Enabled", "Disabled"], var.bucket_versioning)
    error_message = "bucket_versioning must be Enabled or Disabled."
  }
}
variable "bucket_auto_tiering" {
  description = "Optional Object Storage auto-tiering setting."
  type        = string
  default     = null
}
variable "object_events_enabled" {
  description = "Enable Object Storage events on the asset bucket."
  type        = bool
  default     = true
}
variable "kms_key_id" {
  description = "Optional Vault KMS key OCID for bucket and object encryption."
  type        = string
  default     = null
}
variable "bucket_metadata" {
  description = "Metadata applied to the asset bucket."
  type        = map(string)
  default     = {}
}

variable "create_sample_objects" {
  description = "Create synthetic static and private sample objects for smoke tests."
  type        = bool
  default     = false
}
variable "sample_objects" {
  description = "Synthetic objects keyed by logical name. Values supplement or override the built-in samples when create_sample_objects is true."
  type = map(object({
    object_name         = string
    content             = string
    content_type        = optional(string)
    cache_control       = optional(string)
    content_disposition = optional(string)
    content_encoding    = optional(string)
    content_language    = optional(string)
    metadata            = optional(map(string), {})
    storage_tier        = optional(string, "Standard")
  }))
  default = {}
}

variable "preauth_requests" {
  description = "Terraform-managed PARs keyed by logical name. Use only for smoke tests or controlled demos; production short-TTL PARs should be generated by a backend broker."
  type = map(object({
    name                  = optional(string)
    access_type           = optional(string, "ObjectRead")
    object_name           = optional(string)
    bucket_listing_action = optional(string)
    time_expires          = string
  }))
  default = {}
}

variable "create_lifecycle_policy" {
  description = "Create an Object Storage lifecycle policy on the asset bucket."
  type        = bool
  default     = false
}
variable "lifecycle_rules" {
  description = "Object Storage lifecycle rules keyed by logical name."
  type = map(object({
    name               = optional(string)
    action             = string
    is_enabled         = optional(bool, true)
    time_amount        = number
    time_unit          = optional(string, "DAYS")
    target             = optional(string)
    inclusion_patterns = optional(set(string), [])
    exclusion_patterns = optional(set(string), [])
    inclusion_prefixes = optional(set(string), [])
  }))
  default = {}
}

variable "cdn_mode" {
  description = "Edge hand-off mode. Use cloudflare_at_oci for current OCI-first CDN purchases, external_cloudflare for customer-owned Cloudflare, or none for PAR-only delivery."
  type        = string
  default     = "cloudflare_at_oci"

  validation {
    condition     = contains(["cloudflare_at_oci", "external_cloudflare", "none"], var.cdn_mode)
    error_message = "cdn_mode must be cloudflare_at_oci, external_cloudflare, or none."
  }
}
variable "cdn_hostname" {
  description = "Optional customer-facing CDN hostname, such as assets.example.com."
  type        = string
  default     = null
}
variable "create_dns_cname" {
  description = "Create an OCI DNS CNAME for cdn_hostname to the Cloudflare-provided target hostname."
  type        = bool
  default     = false
}
variable "dns_zone_name_or_id" {
  description = "OCI DNS zone name or OCID used when create_dns_cname is true."
  type        = string
  default     = null
}
variable "cdn_target_hostname" {
  description = "Cloudflare-provided target hostname used by the optional OCI DNS CNAME."
  type        = string
  default     = null
}
variable "dns_ttl" {
  description = "TTL in seconds for the optional CDN CNAME record."
  type        = number
  default     = 300
}

variable "create_cloudflare_dns_record" {
  description = "Create a Cloudflare DNS record for the CDN hostname. Requires CLOUDFLARE_API_TOKEN in the execution environment."
  type        = bool
  default     = false
}
variable "cloudflare_zone_id" {
  description = "Cloudflare zone ID for DNS and cache rules."
  type        = string
  default     = null
}
variable "cloudflare_record_name" {
  description = "Cloudflare DNS record name, usually a fully qualified hostname in the selected zone."
  type        = string
  default     = null
}
variable "cloudflare_record_type" {
  description = "Cloudflare DNS record type."
  type        = string
  default     = "CNAME"
}
variable "cloudflare_record_content" {
  description = "Cloudflare DNS record target content, such as the approved origin hostname."
  type        = string
  default     = null
}
variable "cloudflare_record_ttl" {
  description = "Cloudflare DNS record TTL. Use 1 for automatic TTL."
  type        = number
  default     = 1
}
variable "cloudflare_record_proxied" {
  description = "Proxy the DNS record through Cloudflare."
  type        = bool
  default     = true
}
variable "cloudflare_record_comment" {
  description = "Optional Cloudflare DNS record comment."
  type        = string
  default     = null
}
variable "cloudflare_record_tags" {
  description = "Optional Cloudflare DNS record tags."
  type        = set(string)
  default     = []
}
variable "create_cloudflare_cache_ruleset" {
  description = "Create a Cloudflare cache ruleset for approved static asset prefixes. Requires CLOUDFLARE_API_TOKEN with zone ruleset permissions."
  type        = bool
  default     = false
}
variable "cloudflare_cache_ruleset_name" {
  description = "Optional Cloudflare cache ruleset name."
  type        = string
  default     = null
}
variable "cloudflare_cache_ruleset_description" {
  description = "Cloudflare cache ruleset description."
  type        = string
  default     = "Cache approved static asset prefixes for OCI-backed asset delivery."
}
variable "cloudflare_cache_rule_description" {
  description = "Cloudflare cache rule description."
  type        = string
  default     = "Cache approved public static assets."
}
variable "cloudflare_cache_hostname" {
  description = "Hostname matched by the Cloudflare cache rule. Defaults to cdn_hostname or cloudflare_record_name."
  type        = string
  default     = null
}
variable "cloudflare_cache_path_prefix" {
  description = "Path prefix matched by the Cloudflare cache rule."
  type        = string
  default     = "/public/"
}
variable "cloudflare_cache_rule_expression" {
  description = "Optional complete Cloudflare Ruleset expression. Overrides hostname/path prefix expression generation."
  type        = string
  default     = null
}
variable "cloudflare_origin_cache_control" {
  description = "Whether Cloudflare should honor origin Cache-Control headers while applying cache settings."
  type        = bool
  default     = true
}
variable "cloudflare_browser_ttl_mode" {
  description = "Cloudflare browser TTL mode."
  type        = string
  default     = "respect_origin"
}
variable "cloudflare_browser_ttl_seconds" {
  description = "Cloudflare browser TTL seconds when browser TTL mode is override_origin."
  type        = number
  default     = null
}
variable "cloudflare_edge_ttl_mode" {
  description = "Cloudflare edge TTL mode."
  type        = string
  default     = "override_origin"
}
variable "cloudflare_edge_ttl_seconds" {
  description = "Cloudflare edge TTL seconds when edge TTL mode is override_origin."
  type        = number
  default     = 3600
}
variable "cloudflare_disable_stale_while_updating" {
  description = "Disable serving stale content while Cloudflare revalidates content."
  type        = bool
  default     = false
}
variable "create_cloudflare_origin_ruleset" {
  description = "Create a Cloudflare origin rule that routes the disposable CDN hostname to OCI Object Storage."
  type        = bool
  default     = false
}
variable "cloudflare_origin_ruleset_name" {
  description = "Optional Cloudflare origin ruleset name."
  type        = string
  default     = null
}
variable "cloudflare_origin_ruleset_description" {
  description = "Cloudflare origin ruleset description."
  type        = string
  default     = "Route approved CDN hostname traffic to the OCI Object Storage origin."
}
variable "cloudflare_origin_rule_description" {
  description = "Cloudflare origin rule description."
  type        = string
  default     = "Route to OCI Object Storage origin."
}
variable "cloudflare_origin_rule_expression" {
  description = "Optional complete Cloudflare origin rule expression. Defaults to matching the CDN hostname."
  type        = string
  default     = null
}
variable "cloudflare_origin_host" {
  description = "Origin host Cloudflare should route matching requests to. Defaults to objectstorage.<region>.oraclecloud.com."
  type        = string
  default     = null
}
variable "cloudflare_host_header" {
  description = "Optional Host header override for Cloudflare origin routing."
  type        = string
  default     = null
}
variable "cloudflare_sni" {
  description = "Optional SNI override for Cloudflare origin TLS."
  type        = string
  default     = null
}
variable "cloudflare_smoke_test_preauth_key" {
  description = "Optional key from preauth_requests used to build a Cloudflare-routed smoke-test URL."
  type        = string
  default     = null
}
variable "create_cloudflare_worker_proxy" {
  description = "Create a Cloudflare Worker and route that fetches a smoke-test OCI PAR URL without exposing the PAR to the end user."
  type        = bool
  default     = false
}
variable "cloudflare_account_id" {
  description = "Cloudflare account ID for Worker script deployment."
  type        = string
  default     = null
}
variable "cloudflare_worker_script_name" {
  description = "Optional Cloudflare Worker script name."
  type        = string
  default     = null
}
variable "cloudflare_worker_compatibility_date" {
  description = "Cloudflare Worker compatibility date."
  type        = string
  default     = "2024-09-23"
}
variable "cloudflare_worker_route_pattern" {
  description = "Optional Cloudflare Worker route pattern, such as assets.example.com/cloudflare-smoke*."
  type        = string
  default     = null
}
variable "cloudflare_worker_smoke_path" {
  description = "Path used for the Cloudflare Worker smoke-test URL."
  type        = string
  default     = "/cloudflare-smoke"

  validation {
    condition     = startswith(var.cloudflare_worker_smoke_path, "/")
    error_message = "cloudflare_worker_smoke_path must start with /."
  }
}
variable "cloudflare_worker_upstream_preauth_key" {
  description = "Key from preauth_requests used as the Cloudflare Worker upstream PAR URL."
  type        = string
  default     = null
}
variable "cloudflare_worker_upstream_url" {
  description = "Optional explicit upstream URL for the Cloudflare Worker. Prefer cloudflare_worker_upstream_preauth_key for smoke tests."
  type        = string
  default     = null
  sensitive   = true
}
variable "cloudflare_worker_cache_ttl_seconds" {
  description = "Edge cache TTL used by the Cloudflare Worker smoke proxy."
  type        = number
  default     = 300
}
variable "cloudflare_worker_response_cache_control" {
  description = "Cache-Control header returned by the Cloudflare Worker smoke proxy."
  type        = string
  default     = "public, max-age=300, stale-while-revalidate=60"
}

variable "policy_compartment_ocid" {
  description = "Compartment OCID where the optional IAM policy is created. Defaults to tenancy_ocid."
  type        = string
  default     = null
}
variable "policy_statements" {
  description = "Optional IAM policy statements for PAR brokers, asset publishers, and operators."
  type        = list(string)
  default     = []
}
