---
- name: AWS CloudFormation destroy session for hybrid network backbone
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_action: destroy
    aws_stack_name: "{{ lookup('env', 'AWS_BACKBONE_STACK_NAME') | default('oci-aws-hybrid-backbone-dev', true) }}"
    aws_region: "{{ lookup('env', 'AWS_BACKBONE_REGION') | default('eu-west-1', true) }}"
    aws_template_file: "{{ playbook_dir }}/../aws/main.yaml"
    aws_parameters_file: "{{ lookup('env', 'AWS_BACKBONE_PARAMETERS_FILE') | default(playbook_dir ~ '/../aws/parameters.example.json', true) }}"
    aws_capabilities: "CAPABILITY_NAMED_IAM"
  tasks:
    - name: Run shared AWS deployment runner
      ansible.builtin.import_role:
        name: ../../../../ansible/roles/aws_deployment_runner
