# Maintainer: Leandro Michelino | ACE | leandro.michelino@oracle.com
---
- name: OCI landing zone local orchestration
  hosts: localhost
  gather_facts: true
  roles:
    - common
    - oci_cli
    - validation
