# Maintainer: Leandro Michelino | ACE | leandro.michelino@oracle.com
---
landingzone_org: acme
landingzone_region: eu-frankfurt-1
landingzone_region_key: fra
terraform_environment_dir: "{{ playbook_dir }}/../../environments/prod"
terraform_working_dir: "{{ playbook_dir }}/../../blueprints/core"
