# Maintainer: Leandro Michelino | ACE | leandro.michelino@oracle.com
---
- name: Run Terraform destroy for OCI Generative AI Private Landing Zone
  hosts: localhost
  gather_facts: false
  vars:
    terraform_action: destroy
    terraform_backend_enabled: false
    terraform_working_dir: "{{ playbook_dir }}/.."
  roles:
    - terraform_runner
