---
- name: Terraform init without backend
  ansible.builtin.command: terraform init -backend=false
  args:
    chdir: "{{ terraform_working_dir }}"
  changed_when: false

- name: Terraform validate
  ansible.builtin.command: terraform validate
  args:
    chdir: "{{ terraform_working_dir }}"
  changed_when: false

- name: Terraform plan
  ansible.builtin.command: "terraform plan -out={{ terraform_plan_file }}"
  args:
    chdir: "{{ terraform_working_dir }}"
  changed_when: false
